### PR TITLE
Reports Table and submission

### PR DESCRIPTION
**Pull request by andrervincent**
Users may now see all bars in the reports table, 
MakeAReport
ReportsTable

### CODE REVIEW

**Comment by andrervincent** [comment]
[gif link](https://imgur.com/nFEr7LK)

**Comment by jmarealle** [comment]
PPT link & File
https://www.canva.com/design/DAD7owQO4Mg/96hoaGvs6iCNcClT1rqFzQ/view
[HappyHr.pdf](https://github.com/andrervincent/HappyHr/files/4597198/HappyHr.pdf)

**Review by jmarealle — APPROVED** [review]
Looks great

**Comment by Daphne-CPAdmin** [comment]
Please resubmit by attaching your narrated app video in the submission notes or in the readme file. Thank you and Congratulations!

**Comment by andrervincent** [comment]
> Please resubmit by attaching your narrated app video in the submission notes or in the readme file. Thank you and Congratulations!

Narrated walkthrough is now in the readme file. Thanks a bunch!

**Pull request merged**
